"""vacancy dedup key

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 21:02:01.986594
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dedup_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_vacancies_dedup_key'), ['dedup_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancies_dedup_key'))
        batch_op.drop_column('dedup_key')

    # ### end Alembic commands ###
