"""telegram bot

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 21:03:18.537604
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_link_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('telegram_link_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_link_codes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('telegram_username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('notify_min_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_resume_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_users_telegram_chat_id', ['telegram_chat_id'])
        batch_op.create_foreign_key('fk_users_default_resume_id', 'resumes', ['default_resume_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_default_resume_id', type_='foreignkey')
        batch_op.drop_constraint('uq_users_telegram_chat_id', type_='unique')
        batch_op.drop_column('default_resume_id')
        batch_op.drop_column('notify_min_score')
        batch_op.drop_column('telegram_username')
        batch_op.drop_column('telegram_chat_id')

    with op.batch_alter_table('user_vacancies', schema=None) as batch_op:
        batch_op.drop_column('notified_at')

    with op.batch_alter_table('telegram_link_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_link_codes_user_id'))

    op.drop_table('telegram_link_codes')
    # ### end Alembic commands ###
