"""application tracker

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 21:13:12.956327
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_action_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_action_note', sa.String(length=300), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('reminded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_history', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.create_index(batch_op.f('ix_user_vacancies_next_action_at'), ['next_action_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_vacancies_next_action_at'))
        batch_op.drop_column('status_history')
        batch_op.drop_column('reminded_at')
        batch_op.drop_column('next_action_note')
        batch_op.drop_column('next_action_at')
        batch_op.drop_column('applied_at')

    # ### end Alembic commands ###
