"""auto apply

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 09:19:20.340184
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'approved', 'sending', 'applied', 'skipped', 'failed', 'cancelled', name='applicationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('letter', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vacancy_id', name='uq_application_user_vacancy')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_vacancy_id'), ['vacancy_id'], unique=False)

    op.create_table('autoapply_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('min_interval_s', sa.Integer(), nullable=False),
    sa.Column('active_from_hour', sa.Integer(), nullable=False),
    sa.Column('active_to_hour', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('hh_resume_title', sa.String(length=200), nullable=False),
    sa.Column('letter_tone', sa.String(length=16), nullable=False),
    sa.Column('paused_reason', sa.Text(), nullable=False),
    sa.Column('paused_notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autoapply_settings')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_vacancy_id'))
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_sent_at'))
        batch_op.drop_index(batch_op.f('ix_applications_created_at'))

    op.drop_table('applications')
    # ### end Alembic commands ###
